## Part 2: Exercises using the NetworkX library
### Let's try to solve a few of the exercises from the book using NetworkX

### Exercises:

- Go to NS Section 2.12: Homework, then
    - Write the solution exercise 2.1 (the 'Königsberg Problem') from NS in your notebook.
    - Solve exercise 2.3 ('Graph representation') from NS using NetworkX in your notebook. (You don't have to solve the last sub-question about cycles of length 4 ... but I'll be impressed if you do it. One more thing on that last sub-exercise: It's easier to solve if you don't use NetworkX, but simple pen and paper).
    - Solve exercise 2.5 ('Bipartite Networks') from NS using NetworkX in your notebook. Important note: There is a a mistake in the book. When it says "Block diagonal", they mean "Anti-block diagonal" (all elements are away from the diagonal blocks).
    - Note: For those without the physical book (and therefore no exercise numbers), the part "Bipartite Networks - General Considerations" does not need to be solved (the two last questions do not make much sense to me).



### 2.1

All graphs should have max. two nodes with odd degree, to be able to drawn without raising yourpencil from the paper, and without drawing any line more than once. Therefore a, c and d can be drawn, but b cannot.


### 2.3 Graph representation

In [ ]:
import networkx as nx

# Undirected graph
G1 = nx.Graph()
G1.add_nodes_from([1,2,3,4,5,6])
G1.add_edges_from([(1, 2), (1, 3), (1,4), (1,6), (2, 3), (2, 4), (3,6)])

# Directed graph
G2 = nx.DiGraph()
G2.add_nodes_from([1,2,3,4,5,6])
G2.add_edges_from([(1, 2), (2,3), (2,4), (3,2), (3,1), (4,1), (6,1), (6,3)])

# Get adjacency list
adj_list_G1 = list(G1.adjacency())
adj_list_G2 = list(G2.adjacency())

# Get adjacency matrix
adj_matrix_G1 = nx.adjacency_matrix(G1).toarray()
adj_matrix_G2 = nx.adjacency_matrix(G2).toarray()
print("Adjacency Matrix of G1 (Undirected):", adj_matrix_G1)
print("Adjacency Matrix of G2 (Directed):", adj_matrix_G2)

# Get the link list (edge list)
edge_list_G1 = list(G1.edges())
edge_list_G2 = list(G2.edges())
print("Edge List of G1 (Undirected):", edge_list_G1)
print("Edge List of G2 (Directed):", edge_list_G2)




Adjacency Matrix of G1 (Undirected): [[0 1 1 1 0 1]
 [1 0 1 1 0 0]
 [1 1 0 0 0 1]
 [1 1 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]]
Adjacency Matrix of G2 (Directed): [[0 1 0 0 0 0]
 [0 0 1 1 0 0]
 [1 1 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]]
Edge List of G1 (Undirected): [(1, 2), (1, 3), (1, 4), (1, 6), (2, 3), (2, 4), (3, 6)]
Edge List of G2 (Directed): [(1, 2), (2, 3), (2, 4), (3, 2), (3, 1), (4, 1), (6, 1), (6, 3)]


In [64]:
# Clustering coefficient
import numpy as np

C = np.zeros(6)

for n in G1.nodes:
   L = 0
   degree_n = G1.degree(n)
   denominator = degree_n*(degree_n-1)
   nbrs = [nb for nb in G1.neighbors(n)]
   nbrs = np.add(nbrs,-1)
   for nbr in nbrs:
      L += np.sum(adj_matrix_G1[nbr][[nbrs]])/2 #number of connections to the neighbors of n
   if denominator > 0:
      C[n-1] = 2*L/denominator

print(C)

# Alternativt
print(nx.clustering(G1))



[0.5        0.66666667 0.66666667 1.         0.         1.        ]
{1: 0.5, 2: 0.6666666666666666, 3: 0.6666666666666666, 4: 1.0, 5: 0, 6: 1.0}


In [ ]:
# Number of length 4 cycles in the graph (SKAL IKKE LAVES!!!)

A1_4 = np.linalg.matrix_power(adj_matrix_G1, 4)
cycles = np.trace(A1_4)



86


array([26, 19, 19, 11,  0, 11])